GET /favorites?page=0&size=5
Authorization: Basic user1 pwd

#

{
"total" : int,
"page" : int,
"size" : int,
"results" : [
	{ "favId": int,
	  "favName" : String,
	  "iban" : String,
	  "bankName" : String,
	  "status" : String
	}
}

###

POST /favorites
Authorization: Basic user1 pwd
Content-Type: application/json

{
  "favName" : String,
  "iban" : String
}

###

PUT /favorites/{favId}
Authorization: Basic user1 pwd
Content-Type: application/json

{
  "favName" : String,
  "iban" : String
}

###

DELETE /favorites/{favId}
Authorization: Basic user1 pwd
