GET /favorites?page=0&size=5
Authorization: Basic user1 pwd

#

{
"total" : int,
"results" : [
	{ "favId": int,
	  "favName" : String,
	  "iban" : String,
	  "bankName" : String,
	  "status" : String
	}
}

###

