### Get Favorites
GET http://localhost:9090/api/v1/favourites
User-Id: 2

### Create Valid
POST http://localhost:9090/api/v1/favourites
Content-Type: application/json
User-Id: 2

{
  "favName" : "My Denver account",
  "iban" : "PL6112351014000007"
}

### Create Invalid
POST http://localhost:9090/api/v1/favourites
Content-Type: application/json
User-Id: 2

{
  "favName" : "My BNP account",
  "iban" : "PL6110901014000007"
}
