@startwbs
'https://plantuml.com/wbs-diagram
* Hackathon
** Project Setup
*** FavoriteService - Spring boot app
*** BankService - Spring boot app
*** Kafka instance
*** MySql DB
** Login Page
*** Data tables
*** filter Auth Service / Basic Auth\n UserId in header
** Favorite
*** Favorite Validatior
*** Data tables
*** Entity objects
**** Repository
*** View
**** endpoint /favorites
**** pagination
**** FavoriteSearchService
*** Add
**** endpoint POST /favorites
**** FavoriteCreateService
**** Resolve BankCode based on IBAN (kafka)
*** Edit
**** endpoint PUT /favorites/{fvId}
**** FavoriteEditService
**** Resolve BankCode based on IBAN (kafka)
*** Delete
**** endpoint DELETE /favorites/{fvId}
** [LK] Bank Service
*** [LK] Data tables
*** [LK] DRepository
*** [LK] DBankCodeResolverService
*** [LK] Dkafka listener
*** [LK] Dkafka producer


@endwbs