server:
  port: 9091

spring:
  application:
    name: bank-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: changeit
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: bank-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: true

management:
  endpoints:
    web:
      exposure:
        include: "*"